# Generated by Django 5.1.5 on 2026-02-09 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de ativo',
                'verbose_name_plural': 'Tipos de ativos',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('unit', models.CharField(default='un', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item de estoque',
                'verbose_name_plural': 'Itens de estoque',
            },
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=120, unique=True)),
                ('tag', models.CharField(blank=True, max_length=80)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('IN_STOCK', 'Em estoque'), ('IN_USE', 'Em uso'), ('MAINTENANCE', 'Em manutenção'), ('DISCARDED', 'Baixado')], default='IN_STOCK', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sector')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.assettype')),
            ],
            options={
                'verbose_name': 'Ativo (serial)',
                'verbose_name_plural': 'Ativos (serial)',
            },
        ),
        migrations.CreateModel(
            name='AssetMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MOVE', 'Movimentação'), ('STATUS', 'Mudança de status'), ('ASSIGN', 'Mudança de responsável')], default='MOVE', max_length=20)),
                ('from_location', models.CharField(blank=True, max_length=120)),
                ('to_location', models.CharField(blank=True, max_length=120)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('asset_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.assetitem')),
                ('from_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.sector')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('to_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.sector')),
            ],
            options={
                'verbose_name': 'Movimentação de ativo',
                'verbose_name_plural': 'Movimentações de ativos',
                'ordering': ['-moved_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída'), ('ADJUST', 'Ajuste')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.stockitem')),
            ],
            options={
                'verbose_name': 'Movimento de estoque',
                'verbose_name_plural': 'Movimentos de estoque',
                'ordering': ['-moved_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('asset_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.assetitem')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.ticket')),
            ],
            options={
                'verbose_name': 'Ativo no atendimento',
                'verbose_name_plural': 'Ativos no atendimento',
            },
        ),
        migrations.CreateModel(
            name='TicketStockUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.stockitem')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_usages', to='core.ticket')),
            ],
            options={
                'verbose_name': 'Baixa de estoque no atendimento',
                'verbose_name_plural': 'Baixas de estoque no atendimento',
            },
        ),
        migrations.AddIndex(
            model_name='assetitem',
            index=models.Index(fields=['serial'], name='core_asseti_serial_ec6a26_idx'),
        ),
        migrations.AddIndex(
            model_name='assetitem',
            index=models.Index(fields=['status'], name='core_asseti_status_a63522_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketasset',
            unique_together={('ticket', 'asset_item')},
        ),
    ]
