# Generated by ChatGPT on 2026-02-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_fill_ticket_fields(apps, schema_editor):
    Ticket = apps.get_model("core", "Ticket")
    # Preencher novos campos em registros legados
    for t in Ticket.objects.all().iterator():
        changed = False
        if not getattr(t, "subject", ""):
            # Preferir o tipo de serviço como "título" quando existir
            try:
                st = getattr(t, "service_type", None)
                if st:
                    t.subject = f"Atendimento - {st.name}"
                else:
                    t.subject = "Atendimento"
            except Exception:
                t.subject = "Atendimento"
            changed = True
        if not getattr(t, "description", ""):
            base = (getattr(t, "notes", "") or "").strip()
            t.description = base if base else "Importado do sistema anterior."
            changed = True
        # Chamados existentes eram atendimentos já registrados
        if getattr(t, "attended_at", None) and getattr(t, "status", None) in (None, "", "OPEN"):
            t.status = "DONE"
            changed = True
        if changed:
            t.save(update_fields=["subject", "description", "status"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_assettype_stockitem_assetitem_assetmovement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="requester_user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_tickets", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="requester_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="ticket",
            name="subject",
            field=models.CharField(default="Atendimento", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="description",
            field=models.TextField(default="Importado do sistema anterior."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(choices=[("OPEN", "Aberto"), ("IN_PROGRESS", "Em andamento"), ("DONE", "Concluído"), ("CANCELED", "Cancelado")], default="OPEN", max_length=20),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="technician",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="attended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["created_at"], name="core_ticket_created_9d6d5f_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["status"], name="core_ticket_status_82cfe5_idx"),
        ),
        migrations.RunPython(forwards_fill_ticket_fields, migrations.RunPython.noop),
    ]
