# Generated by Django 5.1.5 on 2026-04-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticket_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='core_ticket_created_fe6f19_idx',
            old_name='core_ticket_created_9d6d5f_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='core_ticket_status_f5a85f_idx',
            old_name='core_ticket_status_82cfe5_idx',
        ),
    ]
